[build]
  command = "npm run build --prefix client" # Adjusted for the client folder
  publish = "client/dist"                  # Adjusted for the client folder

[dev]
  framework = "react"       # Replace with your framework (e.g., react, vue, etc.)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
