[build]
  command = "npm run build --prefix client" # Build command for the client folder
  publish = "client/dist"                  # Path to the build output folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
