[build]
  base = "client"                          # Set the base directory to the client folder
  command = "npm run build"                # Build command for the client folder
  publish = "dist"                         # Path to the build output folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
