[build]
  command = "npm install --prefix client && npm run build --prefix client" # Explicitly install and build in the client folder
  publish = "client/dist"                                                 # Path to the build output folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200