[build]
  base = "client"                          # Set the base directory to the client folder
  command = "npm install && npm run build" # Ensure dependencies are installed before building
  publish = "dist"                         # Path to the build output folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200