services:
  - name: ecommerce-backend
    type: web
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    plan: free
    envVars:
      - key: PORT
        value: 5000

staticSites:
  - name: ecommerce-frontend
    buildCommand: cd client && npm install && npm run build
    publishPath: client/dist
    plan: free