services:
  - name: ecommerce-backend
    type: web
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 5000

  - name: ecommerce-frontend
    type: web
    runtime: static
    buildCommand: cd client && npm install && npm run build